# The URL the site will be built for
base_url = "https://totalimpulse.net"
generate_rss = true
compile_sass = true

title = "Total Impulse"

description = "Space Propulsion"

highlight_code = true

highlight_theme = "solarized-light"

taxonomies = [
    {name = "categories", rss = true, paginate_by = 5},
    {name = "tags", rss = true, paginate_by = 5},
]

[extra]
author = "Pete"
clean_blog_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
]
