# The URL the site will be built for
base_url = "https://totalimpulse.net"
generate_rss = true
compile_sass = true

title = "Total Impulse"

description = "Ramblings on propulsion, smallsats, and whatever else seems interesting"

highlight_code = true

highlight_theme = "inspired-github"

taxonomies = [
    {name = "categories", rss = true, paginate_by = 5},
    {name = "tags", rss = true, paginate_by = 5},
]

[extra]
author = "Pete"
clean_blog_menu = [
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/about", name = "About"},
]
